# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc import personal_schedule_pb2 as personal__schedule__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in personal_schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersonalScheduleServiceStub(object):
    """Сервис персонального расписания, позволяет подписываться на расписания и получать информацию об изменениях в них
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSubscribedSchedules = channel.unary_unary(
                '/rtu.schedule.api.PersonalScheduleService/GetSubscribedSchedules',
                request_serializer=personal__schedule__pb2.GetSubscribedSchedulesRequest.SerializeToString,
                response_deserializer=personal__schedule__pb2.GetSubscribedSchedulesResponse.FromString,
                _registered_method=True)
        self.UpdateSubscribedSchedules = channel.unary_unary(
                '/rtu.schedule.api.PersonalScheduleService/UpdateSubscribedSchedules',
                request_serializer=personal__schedule__pb2.UpdateSubscribedSchedulesRequest.SerializeToString,
                response_deserializer=personal__schedule__pb2.UpdateSubscribedSchedulesResponse.FromString,
                _registered_method=True)
        self.GetPersonalScheduleUpdates = channel.unary_unary(
                '/rtu.schedule.api.PersonalScheduleService/GetPersonalScheduleUpdates',
                request_serializer=personal__schedule__pb2.GetPersonalScheduleUpdatesRequest.SerializeToString,
                response_deserializer=personal__schedule__pb2.GetPersonalScheduleUpdatesResponse.FromString,
                _registered_method=True)
        self.AcceptScheduleUpdates = channel.unary_unary(
                '/rtu.schedule.api.PersonalScheduleService/AcceptScheduleUpdates',
                request_serializer=personal__schedule__pb2.AcceptScheduleUpdatesRequest.SerializeToString,
                response_deserializer=personal__schedule__pb2.AcceptScheduleUpdatesResponse.FromString,
                _registered_method=True)
        self.GetScheduleTitle = channel.unary_unary(
                '/rtu.schedule.api.PersonalScheduleService/GetScheduleTitle',
                request_serializer=personal__schedule__pb2.GetScheduleTitleRequest.SerializeToString,
                response_deserializer=personal__schedule__pb2.GetScheduleTitleResponse.FromString,
                _registered_method=True)
        self.GetWrappedSchedule = channel.unary_unary(
                '/rtu.schedule.api.PersonalScheduleService/GetWrappedSchedule',
                request_serializer=personal__schedule__pb2.GetWrappedScheduleRequest.SerializeToString,
                response_deserializer=personal__schedule__pb2.GetWrappedScheduleResponse.FromString,
                _registered_method=True)


class PersonalScheduleServiceServicer(object):
    """Сервис персонального расписания, позволяет подписываться на расписания и получать информацию об изменениях в них
    """

    def GetSubscribedSchedules(self, request, context):
        """Получение расписаний, на которые есть подписка
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSubscribedSchedules(self, request, context):
        """Обновление подписок на расписания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPersonalScheduleUpdates(self, request, context):
        """Получение обновлений по конкретному расписанию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptScheduleUpdates(self, request, context):
        """Принятие (отметка о прочтении) обновлений по расписанию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleTitle(self, request, context):
        """Получение названия расписания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWrappedSchedule(self, request, context):
        """Получение полного расписания в схлопнутом виде
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonalScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSubscribedSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscribedSchedules,
                    request_deserializer=personal__schedule__pb2.GetSubscribedSchedulesRequest.FromString,
                    response_serializer=personal__schedule__pb2.GetSubscribedSchedulesResponse.SerializeToString,
            ),
            'UpdateSubscribedSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSubscribedSchedules,
                    request_deserializer=personal__schedule__pb2.UpdateSubscribedSchedulesRequest.FromString,
                    response_serializer=personal__schedule__pb2.UpdateSubscribedSchedulesResponse.SerializeToString,
            ),
            'GetPersonalScheduleUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonalScheduleUpdates,
                    request_deserializer=personal__schedule__pb2.GetPersonalScheduleUpdatesRequest.FromString,
                    response_serializer=personal__schedule__pb2.GetPersonalScheduleUpdatesResponse.SerializeToString,
            ),
            'AcceptScheduleUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptScheduleUpdates,
                    request_deserializer=personal__schedule__pb2.AcceptScheduleUpdatesRequest.FromString,
                    response_serializer=personal__schedule__pb2.AcceptScheduleUpdatesResponse.SerializeToString,
            ),
            'GetScheduleTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleTitle,
                    request_deserializer=personal__schedule__pb2.GetScheduleTitleRequest.FromString,
                    response_serializer=personal__schedule__pb2.GetScheduleTitleResponse.SerializeToString,
            ),
            'GetWrappedSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWrappedSchedule,
                    request_deserializer=personal__schedule__pb2.GetWrappedScheduleRequest.FromString,
                    response_serializer=personal__schedule__pb2.GetWrappedScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rtu.schedule.api.PersonalScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rtu.schedule.api.PersonalScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersonalScheduleService(object):
    """Сервис персонального расписания, позволяет подписываться на расписания и получать информацию об изменениях в них
    """

    @staticmethod
    def GetSubscribedSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rtu.schedule.api.PersonalScheduleService/GetSubscribedSchedules',
            personal__schedule__pb2.GetSubscribedSchedulesRequest.SerializeToString,
            personal__schedule__pb2.GetSubscribedSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSubscribedSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rtu.schedule.api.PersonalScheduleService/UpdateSubscribedSchedules',
            personal__schedule__pb2.UpdateSubscribedSchedulesRequest.SerializeToString,
            personal__schedule__pb2.UpdateSubscribedSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPersonalScheduleUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rtu.schedule.api.PersonalScheduleService/GetPersonalScheduleUpdates',
            personal__schedule__pb2.GetPersonalScheduleUpdatesRequest.SerializeToString,
            personal__schedule__pb2.GetPersonalScheduleUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptScheduleUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rtu.schedule.api.PersonalScheduleService/AcceptScheduleUpdates',
            personal__schedule__pb2.AcceptScheduleUpdatesRequest.SerializeToString,
            personal__schedule__pb2.AcceptScheduleUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rtu.schedule.api.PersonalScheduleService/GetScheduleTitle',
            personal__schedule__pb2.GetScheduleTitleRequest.SerializeToString,
            personal__schedule__pb2.GetScheduleTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWrappedSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rtu.schedule.api.PersonalScheduleService/GetWrappedSchedule',
            personal__schedule__pb2.GetWrappedScheduleRequest.SerializeToString,
            personal__schedule__pb2.GetWrappedScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
